title: "My name"
description: "Personal Portfolio Website"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mynamemm.github.io" # your domain name or GitHub Pages URL
theme: minima # or any other Jekyll theme you prefer
